version: "3.9"

services:
  backend:
    image: sayapker-16
    container_name: ebook-b16-ev
    restart: always
    ports:
      - "80:2024"
    environment:
      SPRING_PROFILES_ACTIVE: main
      SERVER_PORT: 2024
      POSTGRES_DB:  jdbc:postgresql://database:5432/postgres
      POSTGRES_USER: java16user
      POSTGRES_PASSWORD: java16pass
  database:
    image: postgres:15
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: java16user
      POSTGRES_PASSWORD: java16pass
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

